In [3]:
import pandas

dataframe = pandas.read_csv('student-mat.csv')
print(dataframe.head())

for c in dataframe.columns:
	print(c)
	print(dataframe[c].value_counts(dropna=False))
print(dataframe.columns)

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0      4        3      4     1     1      3        6   5   6   6
1      5        3      3     1     1      3        4   5   5   6
2      4        3      2     2     3      3       10   7   8  10
3      3        2      2     1     1      5        2  15  14  15
4      4        3      2     1     2      5        4   6  10  10

[5 rows x 33 columns]
school
GP    349
MS     46
Name: school, dtype: int64
sex
F    208
M    187
Name: sex, dtype: int64
age
16    104
17     98
18     82
15     82
19     24
20      3
22      1
21      1
Name: age, dtype: int64
address
U    307
R     88
Name: address, dtype: int64
famsize
GT3    281
LE3    114
Name: famsize, dtype: int64
Pstatus
T    354
A     41
Name: Pstatus, dtype: int64
Medu
4    131
2    103
3     99
1     59
0      3
Name: Medu, dtype: int64
Fedu
2    115
3    100
4     96
1     82
0      2
Name: Fedu, dtype: int64
Mjob
other       141
services    103
at_home      59
teacher      58
health       34
Name: Mjob, dtype: int64
Fjob
other       217
services    111
teacher      29
at_home      20
health       18
Name: Fjob, dtype: int64
reason
course        145
home          109
reputation    105
other          36
Name: reason, dtype: int64
guardian
mother    273
father     90
other      32
Name: guardian, dtype: int64
traveltime
1    257
2    107
3     23
4      8
Name: traveltime, dtype: int64
studytime
2    198
1    105
3     65
4     27
Name: studytime, dtype: int64
failures
0    312
1     50
2     17
3     16
Name: failures, dtype: int64
schoolsup
no     344
yes     51
Name: schoolsup, dtype: int64
famsup
yes    242
no     153
Name: famsup, dtype: int64
paid
no     214
yes    181
Name: paid, dtype: int64
activities
yes    201
no     194
Name: activities, dtype: int64
nursery
yes    314
no      81
Name: nursery, dtype: int64
higher
yes    375
no      20
Name: higher, dtype: int64
internet
yes    329
no      66
Name: internet, dtype: int64
romantic
no     263
yes    132
Name: romantic, dtype: int64
famrel
4    195
5    106
3     68
2     18
1      8
Name: famrel, dtype: int64
freetime
3    157
4    115
2     64
5     40
1     19
Name: freetime, dtype: int64
goout
3    130
2    103
4     86
5     53
1     23
Name: goout, dtype: int64
Dalc
1    276
2     75
3     26
5      9
4      9
Name: Dalc, dtype: int64
Walc
1    151
2     85
3     80
4     51
5     28
Name: Walc, dtype: int64
health
5    146
3     91
4     66
1     47
2     45
Name: health, dtype: int64
absences
0     115
2      65
4      53
6      31
8      22
10     17
14     12
12     12
3       8
16      7
7       7
5       5
18      5
20      4
11      3
9       3
13      3
15      3
22      3
1       3
38      1
30      1
40      1
23      1
19      1
28      1
75      1
21      1
24      1
56      1
26      1
54      1
25      1
17      1
Name: absences, dtype: int64
G1
10    51
8     41
11    39
7     37
12    35
13    33
9     31
14    30
15    24
6     24
16    22
18     8
17     8
5      7
19     3
4      1
3      1
Name: G1, dtype: int64
G2
9     50
10    46
12    41
13    37
11    35
15    34
8     32
14    23
7     21
5     15
6     14
16    13
0     13
18    12
17     5
19     3
4      1
Name: G2, dtype: int64
G3
10    56
11    47
0     38
15    33
8     32
13    31
12    31
9     28
14    27
16    16
6     15
18    12
7      9
5      7
17     6
19     5
20     1
4      1
Name: G3, dtype: int64
Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [4]:
from sklearn.model_selection import train_test_split

target = 'internet'
y = dataframe[target]
non_numeric = ['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob',
 	'Fjob', 'reason', 'guardian']
X = dataframe.drop(labels = non_numeric+[target], axis='columns')
# drop non-numberic fields
yes_no = ['activities','schoolsup','famsup','paid','nursery','higher','romantic']
# map yes/no to 1/0
for c in yes_no:
    X[c] = X[c].map({'yes': 1, 'no': 0})

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# see what the data looks like now
print(X.head())
for c in X.columns:
	print(c)
	print(X[c].value_counts(dropna=False))
print(X.columns)

   age  Medu  Fedu  traveltime  studytime  failures  schoolsup  famsup  paid  \
0   18     4     4           2          2         0          1       0     0
1   17     1     1           1          2         0          0       1     0
2   15     1     1           1          2         3          1       0     1
3   15     4     2           1          3         0          0       1     1
4   16     3     3           1          2         0          0       1     1

   activities  ...  famrel  freetime  goout  Dalc  Walc  health  absences  G1  \
0           0  ...       4         3      4     1     1       3         6   5
1           0  ...       5         3      3     1     1       3         4   5
2           0  ...       4         3      2     2     3       3        10   7
3           1  ...       3         2      2     1     1       5         2  15
4           0  ...       4         3      2     1     2       5         4   6

   G2  G3
0   6   6
1   5   6
2   8  10
3  14  15
4  10  10

[5 rows x 23 columns]
age
16    104
17     98
18     82
15     82
19     24
20      3
22      1
21      1
Name: age, dtype: int64
Medu
4    131
2    103
3     99
1     59
0      3
Name: Medu, dtype: int64
Fedu
2    115
3    100
4     96
1     82
0      2
Name: Fedu, dtype: int64
traveltime
1    257
2    107
3     23
4      8
Name: traveltime, dtype: int64
studytime
2    198
1    105
3     65
4     27
Name: studytime, dtype: int64
failures
0    312
1     50
2     17
3     16
Name: failures, dtype: int64
schoolsup
0    344
1     51
Name: schoolsup, dtype: int64
famsup
1    242
0    153
Name: famsup, dtype: int64
paid
0    214
1    181
Name: paid, dtype: int64
activities
1    201
0    194
Name: activities, dtype: int64
nursery
1    314
0     81
Name: nursery, dtype: int64
higher
1    375
0     20
Name: higher, dtype: int64
romantic
0    263
1    132
Name: romantic, dtype: int64
famrel
4    195
5    106
3     68
2     18
1      8
Name: famrel, dtype: int64
freetime
3    157
4    115
2     64
5     40
1     19
Name: freetime, dtype: int64
goout
3    130
2    103
4     86
5     53
1     23
Name: goout, dtype: int64
Dalc
1    276
2     75
3     26
5      9
4      9
Name: Dalc, dtype: int64
Walc
1    151
2     85
3     80
4     51
5     28
Name: Walc, dtype: int64
health
5    146
3     91
4     66
1     47
2     45
Name: health, dtype: int64
absences
0     115
2      65
4      53
6      31
8      22
10     17
14     12
12     12
3       8
16      7
7       7
5       5
18      5
20      4
11      3
9       3
13      3
15      3
22      3
1       3
38      1
30      1
40      1
23      1
19      1
28      1
75      1
21      1
24      1
56      1
26      1
54      1
25      1
17      1
Name: absences, dtype: int64
G1
10    51
8     41
11    39
7     37
12    35
13    33
9     31
14    30
15    24
6     24
16    22
18     8
17     8
5      7
19     3
4      1
3      1
Name: G1, dtype: int64
G2
9     50
10    46
12    41
13    37
11    35
15    34
8     32
14    23
7     21
5     15
6     14
16    13
0     13
18    12
17     5
19     3
4      1
Name: G2, dtype: int64
G3
10    56
11    47
0     38
15    33
8     32
13    31
12    31
9     28
14    27
16    16
6     15
18    12
7      9
5      7
17     6
19     5
20     1
4      1
Name: G3, dtype: int64
Index(['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures',
       'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher',
       'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health',
       'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [5]:
from sklearn import tree

classifier_model = tree.DecisionTreeClassifier()

In [6]:
classifier_model = classifier_model.fit(X_train, y_train)

In [7]:
from sklearn.tree import export_text
from sklearn.metrics import accuracy_score

view_tree = export_text(classifier_model, feature_names=list(X.columns))
print(view_tree)

predictions = classifier_model.predict(X_test)
print(predictions)

print(accuracy_score(y_test, predictions))

|--- Medu <= 1.50
|   |--- absences <= 9.00
|   |   |--- age <= 15.50
|   |   |   |--- class: yes
|   |   |--- age >  15.50
|   |   |   |--- health <= 4.50
|   |   |   |   |--- freetime <= 2.50
|   |   |   |   |   |--- health <= 2.00
|   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |--- health >  2.00
|   |   |   |   |   |   |--- class: no
|   |   |   |   |--- freetime >  2.50
|   |   |   |   |   |--- freetime <= 3.50
|   |   |   |   |   |   |--- goout <= 3.50
|   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |--- goout >  3.50
|   |   |   |   |   |   |   |--- absences <= 2.00
|   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |--- absences >  2.00
|   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |--- freetime >  3.50
|   |   |   |   |   |   |--- paid <= 0.50
|   |   |   |   |   |   |   |--- G3 <= 7.50
|   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |   |--- G3 >  7.50
|   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |--- paid >  0.50
|   |   |   |   |   |   |   |--- class: no
|   |   |   |--- health >  4.50
|   |   |   |   |--- Dalc <= 1.50
|   |   |   |   |   |--- class: no
|   |   |   |   |--- Dalc >  1.50
|   |   |   |   |   |--- traveltime <= 2.50
|   |   |   |   |   |   |--- Medu <= 0.50
|   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |--- Medu >  0.50
|   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |--- traveltime >  2.50
|   |   |   |   |   |   |--- class: yes
|   |--- absences >  9.00
|   |   |--- class: yes
|--- Medu >  1.50
|   |--- age <= 19.50
|   |   |--- paid <= 0.50
|   |   |   |--- G2 <= 12.50
|   |   |   |   |--- G2 <= 10.50
|   |   |   |   |   |--- Walc <= 1.50
|   |   |   |   |   |   |--- traveltime <= 1.50
|   |   |   |   |   |   |   |--- G2 <= 8.50
|   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |--- G2 >  8.50
|   |   |   |   |   |   |   |   |--- G2 <= 9.50
|   |   |   |   |   |   |   |   |   |--- G1 <= 9.50
|   |   |   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |   |   |--- G1 >  9.50
|   |   |   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |   |   |--- G2 >  9.50
|   |   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |--- traveltime >  1.50
|   |   |   |   |   |   |   |--- goout <= 2.50
|   |   |   |   |   |   |   |   |--- G2 <= 7.50
|   |   |   |   |   |   |   |   |   |--- G3 <= 3.00
|   |   |   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |   |   |--- G3 >  3.00
|   |   |   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |   |   |--- G2 >  7.50
|   |   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |--- goout >  2.50
|   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |--- Walc >  1.50
|   |   |   |   |   |   |--- freetime <= 1.50
|   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |--- freetime >  1.50
|   |   |   |   |   |   |   |--- G3 <= 6.50
|   |   |   |   |   |   |   |   |--- G1 <= 7.50
|   |   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |   |--- G1 >  7.50
|   |   |   |   |   |   |   |   |   |--- goout <= 3.50
|   |   |   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |   |   |--- goout >  3.50
|   |   |   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |   |--- G3 >  6.50
|   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |--- G2 >  10.50
|   |   |   |   |   |--- G2 <= 11.50
|   |   |   |   |   |   |--- health <= 1.50
|   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |--- health >  1.50
|   |   |   |   |   |   |   |--- freetime <= 3.50
|   |   |   |   |   |   |   |   |--- absences <= 3.00
|   |   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |   |   |--- absences >  3.00
|   |   |   |   |   |   |   |   |   |--- studytime <= 3.50
|   |   |   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |   |   |--- studytime >  3.50
|   |   |   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |   |--- freetime >  3.50
|   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |--- G2 >  11.50
|   |   |   |   |   |   |--- absences <= 2.50
|   |   |   |   |   |   |   |--- studytime <= 1.50
|   |   |   |   |   |   |   |   |--- G3 <= 13.00
|   |   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |   |--- G3 >  13.00
|   |   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |   |--- studytime >  1.50
|   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |--- absences >  2.50
|   |   |   |   |   |   |   |--- class: yes
|   |   |   |--- G2 >  12.50
|   |   |   |   |--- Fedu <= 3.50
|   |   |   |   |   |--- class: yes
|   |   |   |   |--- Fedu >  3.50
|   |   |   |   |   |--- famsup <= 0.50
|   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |--- famsup >  0.50
|   |   |   |   |   |   |--- Medu <= 3.00
|   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |--- Medu >  3.00
|   |   |   |   |   |   |   |--- age <= 15.50
|   |   |   |   |   |   |   |   |--- G3 <= 16.00
|   |   |   |   |   |   |   |   |   |--- nursery <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |   |   |--- nursery >  0.50
|   |   |   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |   |   |--- G3 >  16.00
|   |   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |--- age >  15.50
|   |   |   |   |   |   |   |   |--- class: yes
|   |   |--- paid >  0.50
|   |   |   |--- goout <= 1.50
|   |   |   |   |--- health <= 4.00
|   |   |   |   |   |--- class: no
|   |   |   |   |--- health >  4.00
|   |   |   |   |   |--- class: yes
|   |   |   |--- goout >  1.50
|   |   |   |   |--- Fedu <= 1.50
|   |   |   |   |   |--- G1 <= 13.50
|   |   |   |   |   |   |--- goout <= 4.50
|   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |--- goout >  4.50
|   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |--- G1 >  13.50
|   |   |   |   |   |   |--- activities <= 0.50
|   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |--- activities >  0.50
|   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |--- Fedu >  1.50
|   |   |   |   |   |--- G1 <= 8.50
|   |   |   |   |   |   |--- G2 <= 9.50
|   |   |   |   |   |   |   |--- Walc <= 3.50
|   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |--- Walc >  3.50
|   |   |   |   |   |   |   |   |--- absences <= 3.50
|   |   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |   |   |--- absences >  3.50
|   |   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |--- G2 >  9.50
|   |   |   |   |   |   |   |--- studytime <= 1.50
|   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |--- studytime >  1.50
|   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |--- G1 >  8.50
|   |   |   |   |   |   |--- G2 <= 8.50
|   |   |   |   |   |   |   |--- G1 <= 10.50
|   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |--- G1 >  10.50
|   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |--- G2 >  8.50
|   |   |   |   |   |   |   |--- age <= 15.50
|   |   |   |   |   |   |   |   |--- Dalc <= 1.50
|   |   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |   |--- Dalc >  1.50
|   |   |   |   |   |   |   |   |   |--- Walc <= 2.50
|   |   |   |   |   |   |   |   |   |   |--- class: no
|   |   |   |   |   |   |   |   |   |--- Walc >  2.50
|   |   |   |   |   |   |   |   |   |   |--- class: yes
|   |   |   |   |   |   |   |--- age >  15.50
|   |   |   |   |   |   |   |   |--- class: yes
|   |--- age >  19.50
|   |   |--- class: no

['yes' 'yes' 'no' 'yes' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes'
 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes'
 'yes' 'yes' 'yes' 'yes' 'yes' 'no' 'yes' 'yes' 'yes' 'no' 'no' 'yes'
 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes'
 'no' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'no' 'yes' 'yes' 'yes'
 'yes' 'yes' 'yes' 'no' 'yes' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes'
 'yes' 'yes' 'yes' 'no' 'yes' 'yes' 'yes']
0.7721518987341772